import NextTopLoader from "nextjs-toploader";
import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import "./globals.css";

import { Navbar } from "@/components/navbar";
import { Sidebar } from "@/components/sidebar";
import { SidebarMobile } from "@/components/sidebar-mobile";

const poppins = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Youtube",
  description: "Clone Youtube Generated by Create Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}   container overflow-hidden overflow-x-hidden `}
      >
        <NextTopLoader color="#ff0000" />
        <header className=" sticky top-0 z-30 w-full">
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
