import NextTopLoader from "nextjs-toploader";
import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import "./globals.css";

import { Navbar } from "@/components/navbar";
import { Sidebar } from "@/components/sidebar";

const poppins = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Youtube",
  description: "Clone Youtube Generated by Create Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  container  overflow-x-hidden `}>
        <NextTopLoader color="#ff0000" />
        <header className=" sticky top-0 z-30 w-full">
          <Navbar />
        </header>

        <div className="flex h-[calc(100vh-56px)] gap-x-5">
          <Sidebar />
          <div className=" h-full flex-1 overflow-y-auto ">{children}</div>
        </div>
      </body>
    </html>
  );
}
